### ISSUE TITLE
You seem to not be dependending on "@angular/core". This is an error. ?

### ISSUE THREAD

**Issue by rainstormza** [stuartkuentzel/mea2n-jwt#1]
Use `pm2 show <id|name>` to get more details about an app
You seem to not be dependending on "@angular/core". This is an error.

npm install and npm start error happen

angular-cli: 1.0.0-beta.24
node: 6.9.1
os: win32 x64

**Comment by stuartwk** [comment]
Thanks for catching that, there was an error in the dependencies which I just updated. In the my-app folder, replace your package with the updated one, then run `npm update`.

**Comment by babusurendra** [comment]
@stuartkuentzel  "npm update" worked for me after installing all dependencies, Thanks!!

**Comment by avanibhatnagar** [comment]
how were you able to update the dependencies?
I ran npm update, but it still gave me the same error

**Comment by githubramakrishnan** [comment]
Delete the node modules and install it again using **npm i**. it's working for me.
